# Generated by Django 2.2.13 on 2022-03-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220306_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articol',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
