# Generated by Django 2.2.13 on 2022-03-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_articol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
