# Generated by Django 2.2.13 on 2022-03-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220316_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='total',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
